using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Net;
using System.Net.Sockets;
using System.Linq;


/**
 * The script that will run at the very begining to init all the necessary info on the server 
 * In reality the server will hold all those info from the blue print of the building
 * However in this demo, data are stored in unity locally, so we have to send them to the server first
 */
public class SceneInitializer : MonoBehaviour
{
    [HideInInspector]
    private String serverIP = "127.0.0.1";
    [HideInInspector]
    private int serverPort = 8081;


    // Start is called before the first frame update
    void Start()
    {
        // connect to the server
        var socket = Utils.connectToServer(this.serverIP, this.serverPort, 1);
        if (socket == null) {
            Debug.Log("fail to connect to server for initialization, skipping this part...");
            return;
        }

        // init the information of height of each floor 
        if (!initFloorHeight(socket)) {
            Debug.Log("fail to init the floor height info of the building in the server");
            socket.Close();
            Utils.quit();
            return;
        }

        // init all the infomation of the sensors 
        if (!initSensors(socket)) {
            Debug.Log("fail to init sensor data in the server!");
            socket.Close();
            Utils.quit();
            return;
        }

        // init all map of all the land marks 
        if (!initLandMarkMap(socket)) {
            Debug.Log("fail to init land mark map in the server!");
            socket.Close();
            Utils.quit();
            return;
        }

        // init the information of all the land marks
        if (!initLandMarkInfo(socket)) {
            Debug.Log("fail to init the land mark info in the server!");
            socket.Close();
            Utils.quit();
            return;
        }

        socket.Close();
    }



    // Update is called once per frame
    void Update()
    {
        
    }



    private bool initFloorHeight(Socket socket) {

        // example: {"1": 1.0, "2": 5.2, ...}

        var floorHeightMessage = "{\"1\": "
                                + GameObject.Find("/Landmark/CleaningH_1").transform.position.y
                                + "}";
        var message_byte = Encoding.UTF8.GetBytes(floorHeightMessage);

        socket.Send(message_byte, message_byte.Length, 0);

        return Utils.acknowledge(socket);
        
    }



    private bool initSensors(Socket socket) {

        var sensorList = GameObject.FindGameObjectsWithTag("sensor");
        var timeOut = 5;

        var message_byte = Encoding.UTF8.GetBytes(buildSensorsMessage(sensorList));
        socket.Send(message_byte, message_byte.Length, 0);

        return Utils.acknowledge(socket);

    }



    private String buildSensorsMessage(GameObject[] sensorList) {

        /* example: 
           {
                "Sensor_LivingRoom_1": {"x": 1.1, "y": 2.2, "height": 3.3, "floor": 1}, 
                "Sensor_LivingRoom_2": {"x": 1.2, "y": 2.3, "height": 3.4, "floor": 1}
            }
         */

        var message = "{";

        for (int i = 0; i < sensorList.Length; i++) {
            message += ("\"" + sensorList[i].name + "\": {");
            message += ("\"x\": " + sensorList[i].transform.position.x + ", ");
            message += ("\"y\": " + sensorList[i].transform.position.z + ", ");
            message += ("\"height\": " + sensorList[i].transform.position.y + ", ");
            message += ("\"floor\": " + sensorList[i].GetComponent<Sensor>().floorNum + "}");
            if (i != sensorList.Length - 1) { message += ", "; }
        }

        message += "}";

        return message;

    }



    private bool initLandMarkMap(Socket socket) {

        var message_byte = Encoding.UTF8.GetBytes(buildMap());
        var timeOut = 5;

        socket.Send(message_byte, message_byte.Length, 0);

        return Utils.acknowledge(socket);

    }



    private String buildMap() {

        var marks = GameObject.FindGameObjectsWithTag("mark");

        var marks_dict = new Dictionary<String, GameObject>();
        foreach (GameObject mark in marks) {
            marks_dict.Add(mark.name, mark);
        }

        return @"
        {""entrance"": {""node_cathy1"": " + Utils.directDistance(marks_dict["entrance"], marks_dict["node_cathy1"]) + @"},
        ""node_cathy1"": {""entrance"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["entrance"]) + @", ""node_cathy2"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["node_cathy2"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["node_cathy3"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["node_cathy4"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["node_cathy5"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["Toilets_1"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["Toilets_2"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["node_bill6"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["cleaning_2"]) + @", ""nodeol8"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["nodeol8"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["cake_x1"]) + @", ""nodeol6"": " + Utils.directDistance(marks_dict["node_cathy1"], marks_dict["nodeol6"]) + @"},
        ""node_cathy2"": {""node_cathy5"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["node_cathy5"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["node_cathy4"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["node_cathy3"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["Toilets_1"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["Toilets_2"]) + @", ""exit"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["exit"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["node_bill6"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["cake_x1"]) + @", ""nodeol6"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["nodeol6"]) + $@", ""node_cathy1"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["node_cathy1"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["cleaning_2"]) + @", ""nodeol8"": " + Utils.directDistance(marks_dict["node_cathy2"], marks_dict["nodeol8"]) + @"},
        ""node_cathy5"": {""node_cathy2"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["node_cathy2"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["node_cathy4"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["node_cathy3"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["Toilets_1"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["Toilets_2"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["node_bill6"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["cake_x1"]) + @", ""nodeol6"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["nodeol6"]) + $@", ""node_cathy1"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["node_cathy1"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["cleaning_2"]) + @", ""nodeol8"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["nodeol8"]) + @", ""Bathroom_x"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["Bathroom_x"]) + @", ""cashier_3"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["cashier_3"]) + @", ""node_bill7"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["node_bill7"]) + @", ""cleaning_1"": " + Utils.directDistance(marks_dict["node_cathy5"], marks_dict["cleaning_1"]) + @"},
        ""node_cathy4"": {""node_cathy2"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_cathy2"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_cathy5"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_cathy3"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["Toilets_1"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["Toilets_2"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_bill6"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["cake_x1"]) + @", ""nodeol6"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["nodeol6"]) + $@", ""node_cathy1"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_cathy1"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["cleaning_2"]) + @", ""nodeol8"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["nodeol8"]) + @", ""Bathroom_x"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["Bathroom_x"]) + @", ""cashier_2"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["cashier_2"]) + @", ""node_bill7"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_bill7"]) + @", ""cleaning_1"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["cleaning_1"]) + @", ""node_bill5"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["node_bill5"]) + @", ""nodeol1"": " + Utils.directDistance(marks_dict["node_cathy4"], marks_dict["nodeol1"]) + @"},
        ""node_cathy3"": {""node_cathy2"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["node_cathy2"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["node_cathy4"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["node_cathy5"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["Toilets_1"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["Toilets_2"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["node_bill6"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["cake_x1"]) + @", ""nodeol6"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["nodeol6"]) + $@", ""node_cathy1"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["node_cathy1"]) + @", ""Book_1"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["Book_1"]) + @", ""Book_2"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["Book_2"]) + @", ""node_bill4"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["node_bill4"]) + @", ""nodeol5"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["nodeol5"]) + @", ""cashier_1"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["cashier_1"]) + @", ""meat_3"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["meat_3"]) + @", ""meat_2"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["meat_2"]) + @", ""meat_1"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["meat_1"]) + @", ""nodeol4"": " + Utils.directDistance(marks_dict["node_cathy3"], marks_dict["nodeol4"]) + @"},
        ""cashier_3"": {""node_cathy5"": " + Utils.directDistance(marks_dict["cashier_3"], marks_dict["node_cathy5"]) + @"},
        ""cashier_2"": {""node_cathy4"": " + Utils.directDistance(marks_dict["cashier_2"], marks_dict["node_cathy4"]) + @"},
        ""cashier_1"": {""node_cathy3"": " + Utils.directDistance(marks_dict["cashier_1"], marks_dict["node_cathy3"]) + @"},
        ""Toilets_1"": {""node_cathy1"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_cathy1"]) + @", ""node_cathy2"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_cathy2"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_cathy3"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_cathy4"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_cathy5"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["Toilets_2"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_bill6"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["cleaning_2"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["cake_x1"]) + @", ""node_bill1"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["node_bill1"]) + @", ""CleaningH_1"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["CleaningH_1"]) + @", ""exit"": " + Utils.directDistance(marks_dict["Toilets_1"], marks_dict["exit"]) + @"},
        ""node_bill3"": {""node_cathy1"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["node_cathy1"]) + @", ""node_cathy2"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["node_cathy2"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["node_cathy3"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["node_cathy4"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["node_cathy5"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["Toilets_1"]) + @", ""node_bill1"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["node_bill1"]) + @", ""CleaningH_1"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["CleaningH_1"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["Toilets_2"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["node_bill6"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["cleaning_2"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["cake_x1"]) + @", ""exit"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["exit"]) + @"},
        ""Toilets_2"": {""node_cathy1"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_cathy1"]) + @", ""node_cathy2"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_cathy2"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_cathy3"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_cathy4"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_cathy5"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_bill3"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["Toilets_1"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_bill6"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["cleaning_2"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["cake_x1"]) + @", ""node_bill1"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["node_bill1"]) + @", ""CleaningH_1"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["CleaningH_1"]) + @", ""exit"": " + Utils.directDistance(marks_dict["Toilets_2"], marks_dict["exit"]) + @"},
        ""node_bill1"": {""node_cathy2"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["node_cathy2"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["node_cathy3"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["node_cathy4"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["node_cathy5"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["Toilets_1"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["node_bill3"], marks_dict["Toilets_2"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["node_bill6"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["cleaning_2"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["cake_x1"]) + @", ""CleaningH_1"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["CleaningH_1"]) + @", ""CleaningH_2"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["CleaningH_2"]) + @", ""Wine_2"": " + Utils.directDistance(marks_dict["node_bill1"], marks_dict["Wine_2"]) + @"},
        ""CleaningH_1"": {""node_cathy2"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["node_cathy2"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["node_cathy3"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["node_cathy4"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["node_cathy5"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["Toilets_1"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["Toilets_2"]) + @", ""node_bill6"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["node_bill6"]) + @", ""cleaning_2"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["cleaning_2"]) + @", ""node_bill2"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["node_bill2"]) + @", ""nodeol7"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["nodeol7"]) + @", ""cake_x1"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["cake_x1"]) + @", ""node_bill1"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["node_bill1"]) + @", ""CleaningH_2"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["CleaningH_2"]) + @", ""Wine_2"": " + Utils.directDistance(marks_dict["CleaningH_1"], marks_dict["Wine_2"]) + @"},
        ""Wine_2"": {""CleaningH_2"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["CleaningH_2"]) + @", ""CleaningH_1"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["CleaningH_2"]) + @", ""node_bill1"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["node_bill1"]) + @", ""Wine_1"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["Wine_1"]) + @", ""Alcohol_2"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["Alcohol_2"]) + @", ""nodeol2"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["nodeol2"]) + @", ""nodeol1"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["nodeol1"]) + @", ""Alcohol_1"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["Alcohol_1"]) + @", ""nodeol3"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["nodeol3"]) + @", ""nodeol5"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["nodeol5"]) + @", ""nodeol4"": " + Utils.directDistance(marks_dict["Wine_2"], marks_dict["nodeol4"]) + @"},
        ""Wine_1"": {""CleaningH_3"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["CleaningH_3"]) + @", ""Wine_3"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["Wine_3"]) + @", ""Wine_2"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["Wine_2"]) + @", ""Alcohol_2"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["Alcohol_2"]) + @", ""nodeol2"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["nodeol2"]) + @", ""nodeol1"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["nodeol1"]) + @", ""Alcohol_1"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["Alcohol_1"]) + @", ""nodeol3"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["nodeol3"]) + @", ""nodeol5"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["nodeol5"]) + @", ""nodeol4"": " + Utils.directDistance(marks_dict["Wine_1"], marks_dict["nodeol4"]) + @"},
        ""Wine_3"": {""Wine_1"": " + Utils.directDistance(marks_dict["Wine_3"], marks_dict["Wine_1"]) + @", ""CleaningH_3"": " + Utils.directDistance(marks_dict["Wine_3"], marks_dict["CleaningH_3"]) + @"},
        ""CleaningH_2"": {""CleaningH_3"": " + Utils.directDistance(marks_dict["CleaningH_2"], marks_dict["CleaningH_3"]) + @", ""CleaningH_4"": " + Utils.directDistance(marks_dict["CleaningH_2"], marks_dict["CleaningH_4"]) + @", ""node_bill7"": " + Utils.directDistance(marks_dict["CleaningH_2"], marks_dict["node_bill7"]) + @", ""cleaning_1"": " + Utils.directDistance(marks_dict["CleaningH_2"], marks_dict["cleaning_1"]) + @", ""CleaningH_1"": " + Utils.directDistance(marks_dict["CleaningH_2"], marks_dict["CleaningH_1"]) + @", ""node_bill1"": " + Utils.directDistance(marks_dict["CleaningH_2"], marks_dict["node_bill1"]) + @", ""Wine_2"": " + Utils.directDistance(marks_dict["CleaningH_2"], marks_dict["Wine_2"]) + @"},
        ""CleaningH_3"": {""CleaningH_2"": " + Utils.directDistance(marks_dict["CleaningH_3"], marks_dict["CleaningH_2"]) + @", ""CleaningH_4"": " + Utils.directDistance(marks_dict["CleaningH_3"], marks_dict["CleaningH_4"]) + @", ""Wine_3"": " + Utils.directDistance(marks_dict["CleaningH_3"], marks_dict["Wine_3"]) + @", ""Wine_1"": " + Utils.directDistance(marks_dict["CleaningH_3"], marks_dict["Wine_1"]) + @", ""node_bill7"": " + Utils.directDistance(marks_dict["CleaningH_3"], marks_dict["node_bill7"]) + @", ""cleaning_1"": " + Utils.directDistance(marks_dict["CleaningH_3"], marks_dict["cleaning_1"]) + @"},
        ""Alcohol_2"": {""Wine_1"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["Wine_1"]) + @", ""Wine_2"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["Wine_2"]) + @", ""nodeol2"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["nodeol2"]) + @", ""Alcohol_1"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["Alcohol_1"]) + @", ""nodeol3"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["nodeol3"]) + @", ""nodeol4"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["nodeol4"]) + @", ""nodeol5"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["nodeol5"]) + @", ""node_bill5"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["node_bill5"]) + @", ""cake_x2"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["cake_x2"]) + @", ""node_bill4"": " + Utils.directDistance(marks_dict["Alcohol_2"], marks_dict["node_bill4"]) + @"},
        ""CleaningH_4"": {""cleaning_1"": " + Utils.directDistance(marks_dict["CleaningH_4"], marks_dict["cleaning_1"]) + @", ""node_bill7"": " + Utils.directDistance(marks_dict["CleaningH_4"], marks_dict["node_bill7"]) + @", ""CleaningH_2"": " + Utils.directDistance(marks_dict["CleaningH_4"], marks_dict["CleaningH_2"]) + @", ""CleaningH_3"": " + Utils.directDistance(marks_dict["CleaningH_4"], marks_dict["CleaningH_3"]) + @", ""Alcohol_2"": " + Utils.directDistance(marks_dict["CleaningH_4"], marks_dict["Alcohol_2"]) + @", ""node_bill5"": " + Utils.directDistance(marks_dict["CleaningH_4"], marks_dict["node_bill5"]) + @", ""nodeol3"": " + Utils.directDistance(marks_dict["CleaningH_4"], marks_dict["nodeol3"]) + @"},
        ""nodeol7"": {""cake_x1"": " + Utils.directDistance(marks_dict["nodeol7"], marks_dict["cake_x1"]) + @", ""node_cathy1"": " + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_cathy1"]) + @", ""node_cathy2"": " + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_cathy2"]) + @", ""node_cathy3"": " + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_cathy3"]) + @", ""node_cathy4"": " + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_cathy4"]) + @", ""node_cathy5"": " + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_cathy5"]) + @", ""nodeol1"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["nodeol2"]) + @", ""nodeol6"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["nodeol6"]) + @",""nodeol8"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["nodeol8"]) + @", ""node_bill1"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_bill1"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_bill2"]) + @",""node_bill3"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_bill3"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_bill5"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_bill6"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["node_bill7"]) + @",""CleaningH_1"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["CleaningH_1"]) + @",""Toilets_1"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["Toilets_1"]) + @",""Toilets_2"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["Toilets_2"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["cleaning_2"]) + @",""Bathroom_x"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["Bathroom_x"]) + @",""cashier_2"":" + Utils.directDistance(marks_dict["nodeol7"], marks_dict["cashier_2"]) + @" },
        ""cake_x1"": {""node_cathy1"": " + Utils.directDistance(marks_dict["cake_x1"], marks_dict["node_cathy1"]) + @", ""node_cathy2"":" + Utils.directDistance(marks_dict["cake_x1"], marks_dict["node_cathy2"]) + @",""node_cathy3"":" + Utils.directDistance(marks_dict["cake_x1"], marks_dict["node_cathy3"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["cake_x1"], marks_dict["node_cathy4"]) + @",""node_cathy5"":" + Utils.directDistance(marks_dict["cake_x1"], marks_dict["node_cathy5"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["cake_x1"], marks_dict["nodeol6"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["cake_x1"], marks_dict["nodeol7"]) + @"},
        ""nodeol6"": {""node_cathy1"": " + Utils.directDistance(marks_dict["nodeol6"], marks_dict["node_cathy1"]) + @", ""node_cathy2"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["node_cathy2"]) + @",""node_cathy3"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["node_cathy3"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["node_cathy4"]) + @",""node_cathy5"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["node_cathy5"]) + @",""cake_x1"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["cake_x1"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["nodeol5"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["nodeol7"]) + @",""cashier_1"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["cashier_1"]) + @",""Book_1"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["Book_1"]) + @",""Book_2"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["Book_2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["node_bill4"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["meat_2"]) + @",""meat_3"":" + Utils.directDistance(marks_dict["nodeol6"], marks_dict["meat_3"]) + @"},
        ""node_bill6"": {""node_cathy1"": " + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_cathy1"]) + @", ""node_cathy2"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_cathy2"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_cathy4"]) + @",""node_cathy5"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_cathy5"]) + @",""node_bill1"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_bill1"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_bill2"]) + @",""node_bill3"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_bill3"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_bill5"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["node_bill7"]) + @",""CleaningH_1"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["CleaningH_1"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["cleaning_1"]) + @",""cleaning_2"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["cleaning_2"]) + @",""Bathroom_x"":" + Utils.directDistance(marks_dict["node_bill6"], marks_dict["Bathroom_x"]) + @"},
        ""node_bill2"": {""node_cathy1"": " + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_cathy1"]) + @", ""node_cathy2"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_cathy2"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_cathy4"]) + @",""node_cathy5"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_cathy5"]) + @",""node_bill1"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_bill1"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_bill6"]) + @",""node_bill3"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_bill3"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_bill5"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["node_bill7"]) + @",""CleaningH_1"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["CleaningH_1"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["cleaning_1"]) + @",""cleaning_2"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["cleaning_2"]) + @",""Bathroom_x"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["Bathroom_x"]) + @",""cashier_2"":" + Utils.directDistance(marks_dict["node_bill2"], marks_dict["cashier_2"]) + @"},
        ""cleaning_2"": {""node_cathy1"": " + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_cathy1"]) + @", ""node_cathy2"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_cathy2"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_cathy4"]) + @",""node_cathy5"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_cathy5"]) + @",""node_bill1"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_bill1"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_bill6"]) + @",""node_bill3"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_bill3"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_bill5"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_bill7"]) + @",""CleaningH_1"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["CleaningH_1"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["cleaning_1"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["node_bill2"]) + @",""Bathroom_x"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["Bathroom_x"]) + @",""cashier_2"":" + Utils.directDistance(marks_dict["cleaning_2"], marks_dict["cashier_2"]) + @"},
        ""Bathroom_x"": {""nodeol1"": " + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["nodeol1"]) + @", ""nodeol2"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["nodeol2"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["nodeol7"]) + @",""nodeol8"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["nodeol8"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["cleaning_1"]) + @",""cleaning_2"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["cleaning_2"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["node_bill2"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["node_bill5"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["node_bill6"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["node_bill7"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["node_cathy4"]) + @",""node_cathy5"":" + Utils.directDistance(marks_dict["Bathroom_x"], marks_dict["node_cathy5"]) + @"},
        ""nodeol8"": {""nodeol1"": " + Utils.directDistance(marks_dict["nodeol8"], marks_dict["nodeol1"]) + @", ""nodeol2"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["nodeol2"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["nodeol7"]) + @",""Bathroom_x"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["Bathroom_x"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["cleaning_1"]) + @",""cleaning_2"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["cleaning_2"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["node_bill2"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["node_bill5"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["node_bill6"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["node_bill7"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["node_cathy4"]) + @",""node_cathy5"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["node_cathy5"]) + @",""cashier_2"":" + Utils.directDistance(marks_dict["nodeol8"], marks_dict["cashier_2"]) + @"},
        ""node_bill7"": {""cleaning_1"": " + Utils.directDistance(marks_dict["node_bill7"], marks_dict["cleaning_1"]) + @", ""Bathroom_x"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["Bathroom_x"]) + @",""nodeol1"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["nodeol2"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["nodeol7"]) + @",""nodeol8"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["nodeol8"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["node_bill2"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["node_bill5"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["node_bill6"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["node_cathy4"]) + @",""CleaningH_2"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["CleaningH_2"]) + @",""CleaningH_3"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["CleaningH_3"]) + @",""CleaningH_4"":" + Utils.directDistance(marks_dict["node_bill7"], marks_dict["CleaningH_4"]) + @"},
        ""cleaning_1"": {""node_bill7"": " + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["node_bill7"]) + @", ""Bathroom_x"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["Bathroom_x"]) + @",""nodeol1"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["nodeol2"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["nodeol7"]) + @",""nodeol8"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["nodeol8"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["node_bill2"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["node_bill5"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["node_bill6"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["node_cathy4"]) + @",""cashier_2"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["cashier_2"]) + @",""CleaningH_2"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["CleaningH_2"]) + @",""CleaningH_3"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["CleaningH_3"]) + @",""CleaningH_4"":" + Utils.directDistance(marks_dict["cleaning_1"], marks_dict["CleaningH_4"]) + @"},
        ""node_bill5"": {""node_bill7"": " + Utils.directDistance(marks_dict["node_bill5"], marks_dict["node_bill7"]) + @", ""node_bill2"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["node_bill2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["node_bill4"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["node_bill6"]) + @",""nodeol1"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["nodeol2"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["nodeol3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["nodeol5"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["nodeol7"]) + @",""nodeol8"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["nodeol8"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["cleaning_1"]) + @",""cleaning_2"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["cleaning_2"]) + @",""Bathroom_x"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["Bathroom_x"]) + @",""CleaningH_3"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["CleaningH_3"]) + @",""CleaningH_4"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["CleaningH_4"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["Wine_1"]) + @",""Alcohol_1"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["Alcohol_1"]) + @",""Alcohol_2"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["Alcohol_2"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["meat_1"]) + @",""cake_x1"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["cake_x1"]) + @",""cashier_2"":" + Utils.directDistance(marks_dict["node_bill5"], marks_dict["cashier_2"]) + @", ""cake_x2"": " + Utils.directDistance(marks_dict["node_bill5"], marks_dict["cake_x2"]) + @"},
        ""cake_x2"": {""node_bill4"": " + Utils.directDistance(marks_dict["cake_x2"], marks_dict["node_bill4"]) + @", ""node_bill5"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["node_bill5"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["meat_2"]) + @",""nodeol1"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["nodeol2"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["nodeol3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["nodeol5"]) + @",""Alcohol_1"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["Alcohol_1"]) + @",""Alcohol_2"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["Alcohol_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["cake_x2"], marks_dict["Wine_2"]) + @"},
        ""node_bill4"": {""node_bill5"": " + Utils.directDistance(marks_dict["node_bill4"], marks_dict["node_bill5"]) + @", ""nodeol1"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["nodeol2"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["nodeol3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["nodeol5"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["nodeol6"]) + @",""Alcohol_1"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["Alcohol_1"]) + @",""Alcohol_2"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["Alcohol_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["Wine_2"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["meat_2"]) + @",""meat_3"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["meat_3"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["cake_x2"]) + @",""Book_1"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["Book_1"]) + @",""Book_2"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["Book_2"]) + @",""node_cathy3"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["node_cathy3"]) + @",""cashier_1"":" + Utils.directDistance(marks_dict["node_bill4"], marks_dict["cashier_1"]) + @"},       
        ""nodeol2"": {""Alcohol_1"": " + Utils.directDistance(marks_dict["nodeol2"], marks_dict["Alcohol_1"]) + @", ""Alcohol_2"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["Alcohol_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["Wine_2"]) + @",""nodeol1"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["nodeol1"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["nodeol3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["nodeol5"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["nodeol7"]) + @",""nodeol8"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["nodeol8"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["node_bill2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["node_bill4"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["node_bill5"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["node_bill6"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["node_bill7"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["cake_x2"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["meat_2"]) + @",""CleaningH_4"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["CleaningH_4"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["meat_1"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["cleaning_1"]) + @",""cleaning_2"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["cleaning_2"]) + @",""Bathroom_x"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["Bathroom_x"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["node_cathy4"]) + @",""cashier_2"":" + Utils.directDistance(marks_dict["nodeol2"], marks_dict["cashier_2"]) + @"},
        ""nodeol1"": {""Alcohol_1"": " + Utils.directDistance(marks_dict["nodeol1"], marks_dict["Alcohol_1"]) + @", ""Alcohol_2"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["Alcohol_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["Wine_2"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["nodeol2"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["nodeol3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["nodeol5"]) + @",""nodeol7"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["nodeol7"]) + @",""nodeol8"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["nodeol8"]) + @",""node_bill2"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["node_bill2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["node_bill4"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["node_bill5"]) + @",""node_bill6"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["node_bill6"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["node_bill7"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["cake_x2"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["meat_2"]) + @",""CleaningH_4"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["CleaningH_4"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["meat_1"]) + @",""cleaning_1"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["cleaning_1"]) + @",""cleaning_2"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["cleaning_2"]) + @",""Bathroom_x"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["Bathroom_x"]) + @",""node_cathy4"":" + Utils.directDistance(marks_dict["nodeol1"], marks_dict["node_cathy4"]) + @"},
        ""Alcohol_1"": {""Alcohol_2"": " + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["Alcohol_2"]) + @", ""nodeol1"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["nodeol2"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["nodeol3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["nodeol5"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["meat_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["Wine_2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["node_bill4"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["node_bill5"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["node_bill7"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["Alcohol_1"], marks_dict["cake_x2"]) + @"},
        ""nodeol3"": {""Alcohol_2"": " + Utils.directDistance(marks_dict["nodeol3"], marks_dict["Alcohol_2"]) + @", ""nodeol1"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["nodeol2"]) + @",""Alcohol_1"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["Alcohol_1"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["nodeol5"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["meat_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["Wine_2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["node_bill4"]) + @",""node_bill5"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["node_bill5"]) + @",""node_bill7"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["node_bill7"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["nodeol3"], marks_dict["cake_x2"]) + @"},  
        ""nodeol5"": {""node_bill5"": " + Utils.directDistance(marks_dict["nodeol5"], marks_dict["node_bill5"]) + @", ""nodeol1"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["nodeol2"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["nodeol3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["nodeol4"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["node_bill4"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["nodeol6"]) + @",""Alcohol_1"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["Alcohol_1"]) + @",""Alcohol_2"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["Alcohol_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["Wine_2"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["meat_2"]) + @",""meat_3"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["meat_3"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["cake_x2"]) + @",""Book_1"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["Book_1"]) + @",""Book_2"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["Book_2"]) + @",""node_cathy3"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["node_cathy3"]) + @",""cashier_1"":" + Utils.directDistance(marks_dict["nodeol5"], marks_dict["cashier_1"]) + @"},       
        ""nodeol4"": {""node_bill5"": " + Utils.directDistance(marks_dict["nodeol4"], marks_dict["node_bill5"]) + @", ""nodeol1"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["nodeol2"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["nodeol3"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["nodeol5"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["node_bill4"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["nodeol6"]) + @",""Alcohol_1"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["Alcohol_1"]) + @",""Alcohol_2"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["Alcohol_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["Wine_2"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["meat_2"]) + @",""meat_3"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["meat_3"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["cake_x2"]) + @",""Book_1"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["Book_1"]) + @",""Book_2"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["Book_2"]) + @",""node_cathy3"":" + Utils.directDistance(marks_dict["nodeol4"], marks_dict["node_cathy3"]) + @"},      
        ""meat_1"": {""node_bill5"": " + Utils.directDistance(marks_dict["meat_1"], marks_dict["node_bill5"]) + @", ""nodeol1"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["nodeol1"]) + @",""nodeol2"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["nodeol2"]) + @",""nodeol3"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["nodeol3"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["nodeol5"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["node_bill4"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["nodeol6"]) + @",""Alcohol_1"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["Alcohol_1"]) + @",""Alcohol_2"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["Alcohol_2"]) + @",""Wine_1"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["Wine_1"]) + @",""Wine_2"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["Wine_2"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["nodeol4"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["meat_2"]) + @",""meat_3"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["meat_3"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["cake_x2"]) + @",""Book_1"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["Book_1"]) + @",""Book_2"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["Book_2"]) + @",""node_cathy3"":" + Utils.directDistance(marks_dict["meat_1"], marks_dict["node_cathy3"]) + @"},
        ""meat_2"": {""node_cathy3"": " + Utils.directDistance(marks_dict["meat_2"], marks_dict["node_cathy3"]) + @", ""nodeol3"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["nodeol3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["nodeol5"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["nodeol6"]) + @",""Book_1"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["Book_1"]) + @",""Book_2"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["Book_2"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["meat_1"]) + @",""meat_3"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["meat_3"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["node_bill4"]) + @",""cake_x2"":" + Utils.directDistance(marks_dict["meat_2"], marks_dict["cake_x2"]) + @"},
        ""meat_3"": {""node_cathy3"": " + Utils.directDistance(marks_dict["meat_3"], marks_dict["node_cathy3"]) + @", ""nodeol4"":" + Utils.directDistance(marks_dict["meat_3"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["meat_3"], marks_dict["nodeol5"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["meat_3"], marks_dict["nodeol6"]) + @",""Book_1"":" + Utils.directDistance(marks_dict["meat_3"], marks_dict["Book_1"]) + @",""Book_2"":" + Utils.directDistance(marks_dict["meat_3"], marks_dict["Book_2"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["meat_3"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["meat_3"], marks_dict["meat_2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["meat_3"], marks_dict["node_bill4"]) + @"},
        ""Book_1"": {""cashier_1"": " + Utils.directDistance(marks_dict["Book_1"], marks_dict["cashier_1"]) + @", ""node_cathy3"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["node_cathy3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["nodeol5"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["nodeol6"]) + @",""meat_3"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["meat_3"]) + @",""Book_2"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["Book_2"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["meat_2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["Book_1"], marks_dict["node_bill4"]) + @"},
        ""Book_2"": {""cashier_1"": " + Utils.directDistance(marks_dict["Book_2"], marks_dict["cashier_1"]) + @", ""node_cathy3"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["node_cathy3"]) + @",""nodeol4"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["nodeol4"]) + @",""nodeol5"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["nodeol5"]) + @",""nodeol6"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["nodeol6"]) + @",""meat_3"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["meat_3"]) + @",""Book_1"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["Book_1"]) + @",""meat_1"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["meat_1"]) + @",""meat_2"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["meat_2"]) + @",""node_bill4"":" + Utils.directDistance(marks_dict["Book_2"], marks_dict["node_bill4"]) + @"},
        ""exit"": {""node_cathy2"": " + Utils.directDistance(marks_dict["exit"], marks_dict["node_cathy2"]) + @", ""Toilets_1"": " + Utils.directDistance(marks_dict["exit"], marks_dict["Toilets_1"]) + @", ""node_bill3"": " + Utils.directDistance(marks_dict["exit"], marks_dict["node_bill3"]) + @", ""Toilets_2"": " + Utils.directDistance(marks_dict["exit"], marks_dict["Toilets_2"]) + @"}}
        ";

    }



    private bool initLandMarkInfo(Socket socket) {

        var marks = GameObject.FindGameObjectsWithTag("mark");
        var timeOut = 5;

        var message = "{";
        for (int i = 0; i < marks.Length; i++) {
            var markPosition = marks[i].transform.position;
            message += ("\"" + marks[i].name + "\"" + ": {\"x\": " + markPosition.x + ", \"y\": " + markPosition.z + ", \"height\": " + markPosition.y + "}");
            if (i != marks.Length - 1) { message += ","; }
        }
        message += "}";

        var message_byte = Encoding.UTF8.GetBytes(message);
        socket.Send(message_byte, message_byte.Length, 0);

        return Utils.acknowledge(socket);

    }
    
}
